name: pr

on:
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:
    branches: [ '**' ]

jobs:
  full_ci:
    strategy:
      matrix:
        go-version: [ 1.14.x ]

    runs-on: ubuntu-18.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        run: go test -json ./... > test.json

      - name: Annotate tests
        if: always()
        uses: guyarb/golang-test-annotations@modifications
        with:
          test-results: test.json

      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: test.json

      - name: path does not exists
        if: always()
        uses: guyarb/golang-test-annotations@modifications
        with:
          test-results: does-not-exist.json

