name: pr

on:
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:
    branches: [ '**' ]

jobs:
  full_ci:
    strategy:
      matrix:
        go-version: [ 1.14.x ]

    runs-on: ubuntu-18.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        run: go test -json ./... > test.json

      - name: Annotate tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.4.0
        with:
          test-results: test.json

      - name: Special package name tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.4.0
        with:
          test-results: test.json
          package-name: mytest

      - name: path does not exists - ignore
        if: always()
        uses: guyarb/golang-test-annotations@v0.4.0
        with:
          test-results: does-not-exist.json
          if-no-files-found: ignore

      - name: path does not exists - warn
        if: always()
        uses: guyarb/golang-test-annotations@v0.4.0
        with:
          test-results: does-not-exist.json
          if-no-files-found: warn

      - name: path does not exists - invalid command
        if: always()
        uses: guyarb/golang-test-annotations@v0.4.0
        with:
          test-results: does-not-exist.json
          if-no-files-found: bla

      - name: path does not exists - error
        if: always()
        uses: guyarb/golang-test-annotations@v0.4.0
        with:
          test-results: does-not-exist.json
          if-no-files-found: error
